### PR TITLE
Fix/enable parity

### PR DESCRIPTION
**Pull request by JoshSinghONS**
### What

Added commits from master which were not in develop and fixed merge conflicts.

### How to review

LGTM.

### Who can review

Anyone.

### CODE REVIEW

**Comment by rafahop** [comment]
Aren't these different commits to the ones in master? Could we merge master instead so that both develop and master are aligned?

**Comment by JoshSinghONS** [comment]
> Aren't these different commits to the ones in master? Could we merge master instead so that both develop and master are aligned?

These are cherry picked from master. Would it not yield the same result?

Saves me discarding all the different changes between master and develop as well as well as trying to fix the numerous merge conflicts.

**Comment by rafahop** [comment]
Well kind of, the code will match but we will have duplicated commits with half of them not present in develop which is not right. It seems like a simple change so the conflicts should be quite easy to fix?

**Comment by JoshSinghONS** [comment]
> Well kind of, the code will match but we will have duplicated commits with half of them not present in develop which is not right. It seems like a simple change so the conflicts should be quite easy to fix?

https://github.com/ONSdigital/florence/pull/891

**Pull request closed without merging**
