### PR TITLE
Trigger Cantabular dataset import in Florence

### PR DESCRIPTION
**Pull request by mr-nick17**
### What

- Show/hide file input fields depending on recipe format
- Increased guard clauses to handle properties that are not returned for Cantabular types
- Updated PUT method to contain `links` array if the format is Cantabular
- Added a `failed` message if the API returns that status

### How to review

Triggering a Cantabular recipe dataset import will currently return a result of `failed` 😲. This is expected as there is ongoing backend work to handle the changes. However, there is testing that can be done to ensure that the toggles are working for the file input field and the `PUT` payload is different between Cantabular and non-Cantabular.  

##### Run the following services 
- The `catabular-import` section of `dp-compose` contains a docker container that runs the necessary backend services needed to import a cantabular dataset. 
  - Go to the subfolder `cantabular-import` of `dp-compose`
  - `./run-cantabular`
  - If you don't have any recipes under the `datasets` section in Florence, update this container with them by running the [import recipes script](https://github.com/ONSdigital/dp-recipe-api/tree/develop/import-recipes)
- dp-api-router
- Babbage 
- Sixteens
- Florence `make dev ENABLE_DATASET_IMPORTS=true` (N.B. I've been using `make dev` as it rebuilds the `node-modules` each time  and then runs the service but you can follow the usual steps if you prefer) 

##### Check the following
1. Check there is no file upload field for a Cantabular recipe 
i.e.
- Login to Florence
- Go to Datasets
- Choose a Cantabular recipe 
Screenshot 2021-08-02 at 10 05 42
2. Check the `POST` to `jobs` and the response in the network tools in Chrome
Screenshot 2021-08-02 at 10 07 58

The `POST` object should be something like this:
```
{
    "recipe": "38542eb6-d3a6-4cc4-ba3f-32b25f23223a"
}
```
The response should be similar to this:
```
{
    "files": [],
    "id": "44dd8b89-413b-495c-9346-17ee93367475",
    "last_updated": "2021-08-02T09:07:20.559Z",
    "links": {
        "instances": [
            {
                "href": "http://api.localhost:23200/v1/instances/0619941d-5c98-4647-b458-2588732031c0",
                "id": "0619941d-5c98-4647-b458-2588732031c0"
            }
        ],
        "self": {
            "href": "http://api.localhost:23200/v1/jobs/44dd8b89-413b-495c-9346-17ee93367475",
            "id": "44dd8b89-413b-495c-9346-17ee93367475"
        }
    },
    "processed_instances": [
        {
            "id": "0619941d-5c98-4647-b458-2588732031c0",
            "required_count": 5
        }
    ],
    "recipe": "38542eb6-d3a6-4cc4-ba3f-32b25f23223a",
    "state": "created"
}
```

3. Check the `PUT` payload object contains the `links` array and a 200 response  is returned 
Screenshot 2021-08-02 at 10 16 16

The payload object should be something like this:
```
{
    "state": "submitted",
    "links": {
        "instances": [
            {
                "href": "http://api.localhost:23200/v1/instances/0619941d-5c98-4647-b458-2588732031c0",
                "id": "0619941d-5c98-4647-b458-2588732031c0"
            }
        ],
        "self": {
            "href": "http://api.localhost:23200/v1/jobs/44dd8b89-413b-495c-9346-17ee93367475",
            "id": "44dd8b89-413b-495c-9346-17ee93367475"
        }
    }
}
```

4. If successful, you'll land on the submitted dataset screen and the poll will eventually return a fail. This means everything is working as expected 😲 

Screenshot 2021-08-02 at 10 19 09

5. Check the upload process still works as expected. You will need to run additional services as per the [instructions](https://github.com/ONSdigital/dp/blob/main/guides/INSTALLING.md#cmd). 
 
Alternatively, you can: 
- Run `dp-upload-service`
- Select a non-Cantabular recipe 
- Check the file upload field is displayed
- Upload a file
- Continue to follow onscreen instructions 
- Check the `PUT` object doesn't contain the `links` array 
  - Payload should look something like this:
  ```
  {
    "state": "submitted"
   }
  ```

Screenshot 2021-08-02 at 10 46 33

### Who can review

- Anyone who knows JS

### CODE REVIEW

**Comment by cookel2** [comment]
I tried the first step (in florence - make dev ENABLE_DATASET_IMPORTS=true) but I ended up with "error": "Get \"http://localhost:23200/health\": dial tcp [::1]:23200: connect: connection refused". Am I doing something wrong?

**Comment by mr-nick17** [comment]
> I tried the first step (in florence - make dev ENABLE_DATASET_IMPORTS=true) but I ended up with "error": "Get "[http://localhost:23200/health\](http://localhost:23200/health%5C)": dial tcp [::1]:23200: connect: connection refused". Am I doing something wrong?

Try starting the `dp-api-router` first

**Comment by cookel2** [comment]
I started the dp-api-router first but now Florence gives me this error instead: "invalid response from downstream service - should be: 200, got: 500, path: /health". When I've run Florence locally in the past there have been about 11 services (including dp-api-router) that I've needed to run before running Florence. Do you think I need to run those?

**Comment by mr-nick17** [comment]
> I started the dp-api-router first but now Florence gives me this error instead: "invalid response from downstream service - should be: 200, got: 500, path: /health". When I've run Florence locally in the past there have been about 11 services (including dp-api-router) that I've needed to run before running Florence. Do you think I need to run those?

The `cantabular-import` subfolder of `dp-compose` contains a docker image of the services you need and the additional ones are listed above. I've not ordered in which way the services should be started but will update the list for you now.

**Comment by cookel2** [comment]
cool, thanks

**Comment by cookel2** [comment]
I can't find a file named "run-cantabular.sh" in dp-compose but can find one named "run-cantabular-without-sudo.sh". Is that thee one to use? 
calling run-cantabular in dp-compose

**Comment by mr-nick17** [comment]
> I can't find a file named "run-cantabular.sh" in dp-compose but can find one named "run-cantabular-without-sudo.sh". Is that the one to use?
> calling run-cantabular in dp-compose

Yes, try that. The file has been renamed since I wrote the PR. I suggest we move this setup conversation to slack where I can help/provide suggestions quicker

**Review by cookel2 — APPROVED** [review]
Thanks for giving me a demo and walking me through the code. It looks good.

**Pull request merged**
